openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /api/v1/tasks:
    get:
      summary: List authenticated user's tasks
      responses:
        '200':
          description: List of tasks
    post:
      summary: Create a new task
      responses:
        '201':
          description: Task created
  /api/v1/tasks/{id}:
    get:
      summary: Get task details
    patch:
      summary: Update task
    delete:
      summary: Delete task
